### ISSUE TITLE
对整个项目的疑惑及可能的开发者推荐

### ISSUE THREAD

**Issue by XingYuan55** [C418-11/MinecraftFunctionCompiler#1]
我是之前玩海岸那个wanghany
  一
我已经将此仓库fork并把fork后的仓库（SSH：git@github.com:XingYuan55/MinecraftFunctionCompiler.git）clone到本地了。正在研读代码。
读代码时我并未理解该项目的用处，是将python代码“翻译”成mcFunction吗？还是别的？我没有理解这个项目的中心。
  二
我还知道一个玩mc喜欢编程的：[IAFEnvoy](https://github.com/IAFEnvoy/)（其个人站：[冰火の小窝](https://www.iafenvoy.com/#)）虽说不经常编py，但是你可以试试

敬礼！

**Comment by C418-11** [comment]
别往issues里放，你不是有我QQ吗，就算不用QQ你不能往discussions里放吗

**Comment by C418-11** [comment]
最新代码请看python-interpreter分支
main是原技术路线“翻译”
python-interpreter是新技术路线“中间码-&gt;解释器”




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "C418-11/MinecraftFunctionCompiler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月11日(星期四) 上午10:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[C418-11/MinecraftFunctionCompiler] 对整个项目的疑惑及可能的开发者推荐 (Issue #1)





 
我是之前玩海岸那个wanghany
 一
 ***@***.***:XingYuan55/MinecraftFunctionCompiler.git）clone到本地了。正在研读代码。
 读代码时我并未理解该项目的用处，是将python代码“翻译”成mcFunction吗？还是别的？我没有理解这个项目的中心。
 二
 我还知道一个玩mc喜欢编程的：IAFEnvoy（其个人站：冰火の小窝）虽说不经常编py，但是你可以试试
 
敬礼！

**Comment by XingYuan55** [comment]
好的。我不往issue放没用的了，谢谢。
